# Generated by Django 6.1 on 2026-08-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qrs/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(default='INR', editable=False, max_length=10),
        ),
    ]
