# Generated by Django 6.0.8 on 2026-09-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_upi_qr_code_alter_event_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="upi_qr_base64",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Permanent Base64 QR Image stored in DB",
            ),
        ),
    ]
