# Generated by Django 6.0.8 on 2026-09-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_upi_qr_base64"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_capacity",
            field=models.PositiveIntegerField(
                blank=True,
                default=1000,
                help_text="Set to blank or None for unlimited attendee capacity",
                null=True,
            ),
        ),
    ]
