# Generated by Django 6.1 on 2026-08-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='payment_proofs/%Y/%m/')),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Structured OCR attributes (amount, txn_id, date, payee)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='payments.order')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('AUTO_VERIFIED', 'Auto Verified by AI/Rules'), ('MANUAL_APPROVED', 'Manually Approved'), ('MANUAL_REVIEW', 'Needs Manual Review'), ('REJECTED', 'Payment Rejected / Invalid'), ('PENDING', 'Pending Verification')], db_index=True, default='PENDING', max_length=30)),
                ('is_amount_matched', models.BooleanField(default=False)),
                ('is_duplicate_txn', models.BooleanField(default=False)),
                ('is_txn_id_found', models.BooleanField(default=False)),
                ('is_payee_matched', models.BooleanField(default=False)),
                ('ocr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ocr_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ocr_payee', models.CharField(blank=True, max_length=255, null=True)),
                ('ocr_timestamp_str', models.CharField(blank=True, max_length=100, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='verification.paymentevidence')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='payments.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
