# Generated by Django 6.0.8 on 2026-09-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentevidence",
            name="image_base64",
            field=models.TextField(
                blank=True,
                help_text="Permanent Base64 Image data for Supabase/Serverless persistence",
            ),
        ),
        migrations.AlterField(
            model_name="paymentevidence",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="payment_proofs/%Y/%m/"
            ),
        ),
    ]
