# Generated by Django 6.0.8 on 2026-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="reg_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Permanent unique 9-char Reg ID (XXX-XXX-XXX) for individual",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registration_code",
            field=models.CharField(
                db_index=True,
                help_text="Unique Reg ID (XXX-XXX-XXX)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
