# Generated by Django 6.1 on 2026-08-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('UPLOADED', 'Proof Uploaded'), ('VERIFYING', 'Verifying Payment'), ('VERIFIED', 'Payment Verified'), ('FAILED', 'Payment Failed'), ('MANUAL_REVIEW', 'Manual Review Required')], db_index=True, default='PENDING', max_length=30)),
                ('upi_intent_url', models.TextField(blank=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_upi', models.CharField(blank=True, max_length=100)),
                ('payee_upi', models.CharField(blank=True, max_length=100)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
