# Generated by Django 6.0.8 on 2026-09-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="qr_code_base64",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Permanent Base64 QR Image stored in DB",
            ),
        ),
    ]
