# Generated by Django 6.1 on 2026-08-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='System', max_length=255)),
                ('action', models.CharField(choices=[('REGISTRATION_CREATED', 'Registration Created'), ('PAYMENT_SESSION_CREATED', 'Payment Session Created'), ('UPI_INTENT_GENERATED', 'UPI Intent Generated'), ('PAYMENT_PROOF_UPLOADED', 'Payment Proof Uploaded'), ('OCR_STARTED', 'OCR Started'), ('OCR_COMPLETED', 'OCR Completed'), ('AMOUNT_MATCHED', 'Amount Matched'), ('TRANSACTION_ID_MATCHED', 'Transaction ID Matched'), ('PAYMENT_AUTO_VERIFIED', 'Payment Auto Verified'), ('PAYMENT_MANUAL_REVIEW', 'Payment Flagged for Manual Review'), ('PAYMENT_MANUAL_APPROVED', 'Payment Manually Approved'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('REGISTRATION_STARTED', 'Registration Started'), ('REGISTRATION_SUCCESS', 'Registration Completed Successfully'), ('EMAIL_SENT', 'Email Sent'), ('PARTNER_API_CALL', 'Partner API Call')], db_index=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='e.g. REG-000123 or ORD-000123', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
