# Generated by Django 6.1 on 2026-08-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Registration Form', max_length=255)),
                ('description', models.TextField(blank=True, default='Please fill in the required details to complete your registration.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_form', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('number', 'Number'), ('textarea', 'Long Text / Paragraph'), ('dropdown', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox Toggle')], default='text', max_length=50)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of choices for dropdown or radio')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.form')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('form', 'field_key')},
            },
        ),
    ]
