# Generated by Django 6.1 on 2026-08-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('event_type', models.CharField(choices=[('REGISTRATION_CREATED', 'Registration Created'), ('PAYMENT_PROOF_RECEIVED', 'Payment Proof Received'), ('REGISTRATION_COMPLETED', 'Registration Completed / Confirmed'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('MANUAL_REVIEW_ALERT', 'Manual Review Alert')], default='REGISTRATION_COMPLETED', max_length=50)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('SIMULATED', 'Simulated (In-App)'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
